export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const PRODUCT_NEW_REQUEST = "PRODUCT_NEW_REQUEST"
export const PRODUCT_NEW_SUCCESS = "PRODUCT_NEW_SUCCESS"
export const PRODUCT_NEW_FAIL = "PRODUCT_NEW_FAIL"

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST"
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS"
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL"

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
