export const ALL_VENTAS_REQUEST = "ALL_VENTAS_REQUEST"
export const ALL_VENTAS_SUCCESS = "ALL_VENTAS_SUCCESS"
export const ALL_VENTAS_FAIL = "ALL_VENTAS_FAIL"

export const VENTA_DETAILS_REQUEST = "VENTA_DETAILS_REQUEST"
export const VENTA_DETAILS_SUCCESS = "VENTA_DETAILS_SUCCESS"
export const VENTA_DETAILS_FAIL = "VENTA_DETAILS_FAIL"

export const ALL_CART_REQUEST = "ALL_CART_REQUEST"
export const ALL_CART_SUCCESS = "ALL_CART_SUCCESS"
export const ALL_CART_FAIL = "ALL_CART_FAIL"

export const CART_ITEM_REQUEST = "CART_ITEM_REQUEST"
export const CART_ITEM_SUCCESS = "CART_ITEM_SUCCESS"
export const CART_ITEM_FAIL = "CART_ITEM_FAIL"

export const EDIT_CART_REQUEST = "EDIT_CART_REQUEST"
export const EDIT_CART_SUCCESS = "EDIT_CART_SUCCESS"
export const EDIT_CART_FAIL = "EDIT_CART_FAIL"

export const NEW_VENTAS_REQUEST = "NEW_VENTAS_REQUEST"
export const NEW_VENTAS_SUCCESS = "NEW_VENTAS_SUCCESS"
export const NEW_VENTAS_FAIL = "NEW_VENTAS_FAIL"

export const DEL_CART_REQUEST = "DEL_CART_REQUEST"
export const DEL_CART_SUCCESS = "DEL_CART_SUCCESS"
export const DEL_CART_FAIL = "DEL_CART_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"